config/routes.rb
Immunotoxibase::Application.routes.draw do
  devise_for :users

  match "admin" => "home#admin"

  scope "/admin" do
    resources :sections, except: [:show, :index] do
      collection do
        post :sort
        get :autocomplete_reference_description
      end
    end
    resources :references, except: [:show, :index]
    resources :measures, except: [:show, :index] do
      collection do
        get :tree
        post :rebuild
      end
    end
  end

  get "home/autocomplete_section_name"
  match "toc(/:chapter(/:family(/:molecule)))" => "sections#toc", as: "toc"

  root :to => "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def admin
  end

  def autocomplete_section_name
    term = params[:term]
    if term && term.present?
      items = Section.where(depth: 2).where("LOWER(name) like ?", term.downcase + "%").limit(10).order(:name)
    else
      items = {}
    end
    render json: json_for_autocomplete(items, "name".downcase)
  end
end

app/views/home/admin.html.haml
%h1 Administration menu

%hr

- if can? :tree, Measure
  = link_to tree_measures_path, class: "btn" do
    %i.icon-list.icon-white
    Manage Measures list

app/views/home/index.html.haml
%div.hero-unit
  %h1 IMMUNOTOXIBASE
  %p A comprehensive immunotoxicology database providing the latest available information on the adverse effects on the immune system of all kinds of chemicals including medicinal products, agrochemicals, industrial, household and environmental chemicals, cosmetics, food additives and ingredients, natural substances, and any other chemicals.

%section#contents
  %p
    %strong IMMUNOTOXIBASE
    can be accessed from the
    = link_to "table of contents", toc_path
    including chapters (e.g. antibiotics or insecticides) that are further subdivided into chemical families (e.g. aminosides or organophosphates) where data on each molecule are given individually either as a text or in tabulated format. All cited references are listed at the end of each section devoted to one molecule with hyperlinks enabling direct access to NCBI's Pubmed&reg; or other bibliographic resources whenever available. In addition, the contents of
    %strong IMMUNOTOXIBASE
    can be accessed via a
    = link_to "search tool", "#"
    using keywords such as chapter, chemical, family, molecule, species, endpoint either singly or in combination.

  .main-buttons
    = link_to "Table of contents", toc_path, class: "btn btn-primary btn-large"

  %div.alert.alert-block
    %h4.alert-heading DISCLAIMER:
    The information available in
    %strong IMMUNOTOXIBASE
    can be accessed and distributed freely. Although the data have been carefully checked and are believed to be accurate, anybody mentioning or relying upon the information or opinions set out in IMMUNOTOXIBASE does so at his/her own risk. Neither Prof. Jacques Descotes nor the Association
    = link_to '"Summerschool in Immunotoxicology"', "http://www.school-immunotoxicology.org"
    make any representations or warranties regarding the presented contents. They strongly advise that independent professional judgement is exercised and/or independent professional advice is sought before using or relying upon this information.