config/routes.rb
Immunotoxibase::Application.routes.draw do
  devise_for :users

  match "admin" => "home#admin"

  scope "/admin" do
    resources :sections, except: [:show, :index] do
      collection do
        post :sort
        get :autocomplete_reference_description
      end
    end
    resources :references, except: [:show, :index]
    resources :measures, except: [:show, :index] do
      collection do
        get :tree
        post :rebuild
      end
    end
  end

  get "home/autocomplete_section_name"
  match "toc(/:chapter(/:family(/:molecule)))" => "sections#toc", as: "toc"

  root :to => "home#index"
end

app/models/section.rb
class Section < ActiveRecord::Base
  include TheSortableTree::Scopes
  extend FriendlyId
  friendly_id :name, use: :slugged

  attr_accessible :name, :description, :picture, :maj, :parent_id, :old_id, :assessments_attributes, :slug, :delete_picture

  acts_as_nested_set

  has_attached_file :picture,
                      storage: :s3,
                      bucket: ENV['S3_BUCKET'],
                      s3_credentials: {
                        access_key_id: ENV['S3_KEY'],
                        secret_access_key: ENV['S3_SECRET']
                      }

  validates :name, presence: true

  before_validation :clear_picture

  has_many :assessments, foreign_key: "molecule_id", order: "position"
  has_many :measures, through: :assessments, dependent: :destroy
  has_many :species, through: :assessments, dependent: :destroy

  accepts_nested_attributes_for :assessments, :reject_if => :all_blank, allow_destroy: true

  include PgSearch
  pg_search_scope :search, against: [:name, :description],
    using: {tsearch: {dictionary: "english"}}

  DEPTH = {0 => "chapter", 1 => "family", 2 => "molecule"}

  def depth_name
    depth ? DEPTH[depth] : parent.child_name
  end

  def child_name
    molecule? ? nil : DEPTH[depth + 1]
  end

  def molecule?
    if parent
      depth ? depth == 2 : parent.depth == 1
    else
      false
    end
  end

  def to_s
    name
  end

  def clear_picture
    self.picture = nil if delete_picture? && !picture.dirty?
  end

  def delete_picture=(value)
    @delete_picture = !value.to_i.zero?
  end

  def delete_picture
    !!@delete_picture
  end

  alias_method :delete_picture?, :delete_picture
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  load_and_authorize_resource

  helper_method :current_section_depth

  def sort
    params[:assessments].compact.each_with_index do |id, index|
      Assessment.update_all({position: index+1}, {id: id})
    end
    render nothing: true
  end

  def autocomplete_reference_description
    term = params[:term]
    if term && term.present?
      items = Reference.where("LOWER(description) like ?", term.downcase + "%").limit(20).order(:description)
    else
      items = {}
    end
    render json: json_for_autocomplete(items, :description)
  end

  def toc
    params[:molecule] = params[:molecule].present? ? params[:molecule].downcase : nil
    section = Section.find(params[current_section_depth]) if current_section_depth
    @depth = current_section_depth
    @section = SectionDecorator.find(section) if section
  end

  def new
    if params[:parent_id]
      @parent = Section.find(params[:parent_id])
      @section.parent_id = @parent.id
    end
  end

  def create
    if @section.save
      redirect_to the_toc_path(@section), notice: "Successfully created #{@section}"
    else
      render :new
    end
  end

  def update
    if @section.update_attributes(params[:section])
      redirect_to the_toc_path(@section), notice: "Successfully updated #{@section}"
    else
      render :edit
    end
  end

  def destroy
  end

  private

  def current_section_depth
    if params[:molecule].nil?
      if params[:family].nil?
        if params[:chapter].nil?
          depth = nil
        else
          depth = "chapter"
        end
      else
        depth = "family"
      end
    else
      depth = "molecule"
    end
    @depth ||= depth
  end
end

app/helpers/sections_helper.rb
module SectionsHelper
  def link_to_add_child_of(section)
    if section
      unless section.molecule?
        if can? :create, Section
          link_to(new_section_path(parent_id: section.to_param), class: "btn btn-success") do
            safe_concat(content_tag(:i, nil, class: "icon-plus icon-white") +
            "Add #{section.child_name} for #{section.depth_name}: #{section.name}")
          end
        end
      end
    else
      if can? :create, Section
        link_to(new_section_path, class: "btn btn-success") do
          safe_concat(content_tag(:i, nil, class: "icon-white icon-plus") +
          " Add a new chapter")
        end
      end
    end
  end

  def back_to_record(section)
    if section.new_record?
      parent = Section.find(params[:parent_id]) if params[:parent_id].present?
      if parent
        title = parent.name
        depth_name = parent.depth_name
        target = parent
      else
        return link_to "Back to Table of Contents", toc_path, class: "btn btn-primary"
      end
    else
      title = section.name
      depth_name = section.depth_name
      target = section
    end
    link_to_item(target, false, "Back to #{depth_name} #{title}", "btn btn-primary")
  end

  def children_list(section)
    list = section ? section.children : Section.roots
    children_title = section.depth == 0 ? "Chemical Families" : "Molecules" if section
    html = []
    html << content_tag(:h3, children_title) if section && section.depth != 2
    html << render("list", list: list, list_class: "")
    html.join("").html_safe
  end

  def link_to_item(section, condition=false, name=section.name, css_class = nil)
    link_to_unless(condition, "<i class=\"#{icon_css_class(section)}\"></i> #{name}".html_safe, the_toc_path(section), class: css_class)
  end

  def icon_css_class(section)
    level = section.depth
    icon_class = "icon-white "
    case level
      when 0
        icon_class += "icon-book"
      when 1
        icon_class += "icon-file"
      else
        icon_class += "icon-tint"
      end
  end

  def maj(section)
    if section && section.maj?
      content_tag :span, class: "timestamps" do
        ["(Last update: ",
          content_tag(:time, l(section.maj.to_date, format: :long), datetime: l(section.maj.to_date, format: :long)),
          ")"
        ].join("").html_safe
      end
    end
  end

  def link_to_edit(section)
    if section
      if can? :edit, section
        link_to(edit_section_path(section), class: "btn btn-primary") do
            safe_concat(content_tag(:i, nil, class: "icon-pencil icon-white") + " Edit #{section.depth_name}: #{section.name}")
        end
      end
    end
  end

  def page_title(section)
    title = section ? section.name : "Table of Contents"
    content_tag :h1, title
  end

  def breadcrumb(section, depth)
    if section
      content_tag :div, class: "subnav" do
        content_tag :ul, class: "breadcrumb" do
          lis = []
          lis << toc_crumb
          section.self_and_ancestors.each do |branch|
            lis << crumb(branch, depth)
          end
          lis.join("").html_safe
        end
      end
    end
  end

  private

  def toc_crumb
    content_tag(:li, link_to("Table of Contents", toc_path))
  end

  def crumb_divider(divider=">")
    (content_tag(:span, divider, class: "divider")).html_safe
  end

  def crumb(item, depth)
    current = item.depth_name == depth
    item_class = current ? "active" : nil
    contents = []
    contents << crumb_divider
    contents << link_to_item(item, current)
    content_tag :li, contents.join("").html_safe, class: item_class
  end
end

app/views/sections/_actions.html.haml
= button_tag type: :submit, class: "btn btn-success" do
  %i.icon-white.icon-ok
  Save
= button_tag type: :reset, class: "btn btn-danger" do
  %i.icon-white.icon-remove
  Reset
= back_to_record(section)

app/views/sections/_assessment_fields.html.haml
.nested-fields
  = f.association :measure
  = f.association :species
  = f.input :condition
  = f.input :effet
  = f.input :level
  = f.input :evolution, collection: Assessment::EVOLUTION, as: :radio_buttons, item_wrapper_class: "inline"

  .control-group.reference_id_field
    = f.label :reference_description, "Reference", class: "control-label"
    .controls
      = f.autocomplete_field :reference_description, autocomplete_reference_description_sections_path, class: "span8",id_element: "#section_assessments_attributes_UN_reference_description"
      = link_to "#", data: {link: new_reference_path(modal: true)}, class: "btn btn-primary create" do
        %i.icon-plus.icon-white
        Add new
      = link_to "#", data: {link: edit_reference_path(modal: true, id: "__ID__")}, class: "btn btn-info update" do
        %i.icon-pencil.icon-white
        See/edit
      = f.hidden_field :reference_id, class: "reference_id"
  = f.input :_destroy, as: :hidden
  = link_to_remove_association f, class: "btn btn-danger" do
    %i.icon-white.icon-trash
    Remove Assessment

app/views/sections/_assessments.html.haml
%h3 Tabulated data
%table.table.table-condensed.table-striped#assessments
  %tr
    %th &nbsp;
    %th{colspan: 2} Measured endpoints
    %th Species
    %th Conditions of exposure
    %th Effect
    %th p Level
    %th Ref.
  - AssessmentDecorator.decorate(assessments).each do |assessment|
    = content_tag_for :tr, assessment do
      %td.dragHandle &nbsp;
      %td{data: {value: value = assessment.measure.parent}}= value
      %td{data: {value: value = assessment.measure}}= value
      %td{data: {value: value = assessment.species}}= value
      %td{data: {value: value = assessment.condition}}= value
      %td{data: {value: value = assessment.effet_and_evolution}}= value
      %td{data: {value: value = assessment.level}}= value
      %td{data: {value: reference = assessment.reference}}= link_to reference, "#", rel: "modal", data: {reference: reference.to_s, title: reference.description, authors: reference.name, link: (reference.url if reference.url) }
- if current_user
  = link_to "#", class: "btn btn-info", id: "reorder_assessments" do
    %i.icon-white.icon-resize-vertical
    Reorder assessments
  = link_to "#", class: "btn btn-success", id: "done_reordering", style: "display: none;" do
    %i.icon-white.icon-ok
    Done

app/views/sections/_form.html.haml
= content_for :head do
  %script{type: "text/javascript", src: "/javascripts/wymeditor/jquery.wymeditor.min.js"}

= simple_form_for section, html: {class: "form-horizontal", multipart: true} do |form|
  .actions= render 'actions', section: section
  = form.input :parent_id, as: :hidden
  = form.input :name, input_html: {class: "span5"}
  - unless section.new_record? || !section.picture?
    #current_picture
      = image_tag section.picture.url, alt: "Picture", title: "Current picture"
      %label.checkbox
        = form.check_box :delete_picture
        Delete current picture?
  = form.input :picture, as: :file

  = form.input :description, input_html: {class: "wymeditor"}
  - if section.molecule?
    #assessments
      = form.simple_fields_for :assessments do |assessment|
        = render 'assessment_fields', f: assessment
      .links
        = link_to_add_association form, :assessments, class: "btn btn-primary" do
          %i.icon-white.icon-plus
          Add assessment

  .actions= render 'actions', section: section

:coffeescript
  $(".wymeditor").wymeditor
    skin: 'default'
  $('button[type=submit]').addClass('wymupdate')

app/views/sections/_list.html.haml
%ul{class: "toc #{list_class}"}
  - list.each do |item|
    %li
      = link_to_item(item)
      - children = item.children rescue nil
      - if children && children.any?
        = link_to "#", class: "btn btn-primary toggle-children" do
          %i.icon-plus.icon-white
        = render "list", list: children, list_class: "children"

app/views/sections/_section.html.haml
%article
  %header
    = breadcrumb(section)
    %h1
      = section.name
      = section.link_to_pdf
    = section.maj
    - if can? :edit, section
      = link_to edit_section_path(section), class: "btn btn-inverse" do
        %i.icon-white.icon-pencil
        Edit this #{section.depth_name}
  %hr
  %section.description= simple_format section.description
  %section.children= section.children
  = new_child_of(section)
  %section.assessments= section.assessments
  %footer

app/views/sections/edit.html.haml
%h1 Edit #{@section.depth_name}: #{@section.name}

= render 'form', section: @section

app/views/sections/new.html.haml
%h1
  - if @parent
    New child #{@section.depth_name} for #{@parent.name}
  - else
    New Chapter

= render 'form', section: @section

app/views/sections/toc.html.haml
%article
  %header
    = breadcrumb(@section, @depth)
    = page_title(@section)
    = maj(@section)
  %hr
  - if @section
    %section.picture= image_tag @section.picture.url if @section.picture?
    %section.description= simple_format @section.description
    %section.assessments= render "assessments", assessments: @section.assessments if @section.molecule? and @section.assessments.any?
  = children_list(@section)
  %footer
    = link_to_edit(@section)
    = link_to_add_child_of(@section)