config/routes.rb
Immunotoxibase::Application.routes.draw do
  devise_for :users

  match "admin" => "home#admin"

  scope "/admin" do
    resources :sections, except: [:show, :index] do
      collection do
        post :sort
        get :autocomplete_reference_description
      end
    end
    resources :references, except: [:show, :index]
    resources :measures, except: [:show, :index] do
      collection do
        get :tree
        post :rebuild
      end
    end
  end

  get "home/autocomplete_section_name"
  match "toc(/:chapter(/:family(/:molecule)))" => "sections#toc", as: "toc"

  root :to => "home#index"
end

app/models/measure.rb
class Measure < ActiveRecord::Base
  include TheSortableTree::Scopes
  attr_accessible :name, :parent_id, :old_id

  acts_as_nested_set

  has_many :assessments
  has_many :molecules, through: :assessments, dependent: :destroy, class_name: "Section"

  validate :name, presence: true

  default_scope order(:name)

  def to_s
    name
  end
end

app/controllers/measures_controller.rb
class MeasuresController < ApplicationController
  load_and_authorize_resource
  include TheSortableTreeController::Rebuild

  def tree
    @measures = Measure.nested_set.all
  end

  def new
    if params[:parent_id]
      @parent = Measure.find(params[:parent_id])
      @measure.parent_id = @parent.id
    end
  end

  def create
    if @measure.save
      redirect_to tree_measures_path, notice: "Successfully created #{@measure}"
    else
      render :new
    end
  end

  def edit
    if @measure.parent
      @parent = @measure.parent
    end
  end

  def update
    if @measure.update_attributes(params[:measure])
      redirect_to tree_measures_path, notice: "Successfully updated #{@measure}"
    else
      render :edit
    end
  end

  def destroy
    @measure.destroy
    redirect_to tree_measures_path, notice: "Successfully destroyed #{@measure}"
  end
end

app/views/measures/_form.html.haml
= simple_form_for measure, html: {class: 'form-horizontal', multipart: true} do |form|
  = form.input :parent_id, as: :hidden
  = form.input :name
  .actions
  = button_tag type: :submit, class: "btn btn-success" do
    %i.icon-white.icon-ok
    Save
  = link_to tree_measures_path, class: "btn btn-primary", confirm: "This measure is not saved, are you sure?" do
    %i.icon-white.icon-list
    Back to List

app/views/measures/edit.html.haml
%h1
  - if @parent
    Editing measure: #{@measure.name}
    %small child of #{@parent.name}
  - else
    Editing measure: #{@measure.name}

= render 'form', measure: @measure

app/views/measures/new.html.haml
%h1
  - if @parent
    New child Measure of #{@parent.name}
  - else
    New root Measure

= render 'form', measure: @measure

app/views/measures/tree.html.haml
%h1 Measures Hierarchy

- if @measures.empty?
  %div.alert
    %strong My apologies...
    No measures entries in database.
    %p
      = link_to new_measure_path, class: "btn btn-success" do
        %i.icon-plus.icon-white
        Create your first measure
- else
  = sortable_tree @measures, type: :sortable, path: "measures/sortable/base", new_url: new_measure_path, title: :name