config/routes.rb
Immunotoxibase::Application.routes.draw do
  devise_for :users

  match "admin" => "home#admin"

  scope "/admin" do
    resources :sections, except: [:show, :index] do
      collection do
        post :sort
        get :autocomplete_reference_description
      end
    end
    resources :references, except: [:show, :index]
    resources :measures, except: [:show, :index] do
      collection do
        get :tree
        post :rebuild
      end
    end
  end

  get "home/autocomplete_section_name"
  match "toc(/:chapter(/:family(/:molecule)))" => "sections#toc", as: "toc"

  root :to => "home#index"
end

app/views/layouts/_navigation.html.haml
= link_to "IMMUNOTOXIBASE", root_path, :class => 'brand'
%ul.nav
  %li
    = link_to root_path do
      %i.icon-home.icon-white
      Home
  %li
    = link_to toc_path do
      %i.icon-book.icon-white
      Table of Contents

%ul.nav.pull-right
  %li
    = form_tag toc_path, method: :get, class: "navbar-search" do
      .input-append
        = text_field_tag :molecule, params[:molecule], data: {provide: "typeahead"},
          class: "search-query span2", autocomplete: "off"
        = button_tag class: "btn btn-primary" do
          %i.icon-white.icon-search
  - if user_signed_in?
    %li
      = link_to admin_path do
        %i.icon-cog.icon-white
        Admin
    %li
      = link_to destroy_user_session_path, method: "delete" do
        %i.icon-user.icon-white
        Logout
  - else
    %li
      = link_to new_user_session_path do
        %i.icon-user.icon-white
        Login

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Immunotoxibase"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              - flash.each do |name, msg|
                %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
                  %a.close{"data-dismiss" => "alert"} ×
                  = msg
              = yield
          %footer